language: node_js
os:
  - linux
  - osx
node_js:
  - v15
  - v12
  - v10

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm install
        - travis_wait 30 npm run test